const fs = require('fs');
const path = require('path');
const vm = require('vm');

const dir = __dirname;
const panorama = path.join(dir, '..', 'custom_menu', 'panorama');
const cssPath = path.join(panorama, 'styles', 'custom_game', 'ui.css');
const xmlPath = path.join(panorama, 'layout', 'custom_game', 'menu_ui.xml');

function jsString(value) {
  return JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function writeAssets() {
  const css = fs.readFileSync(cssPath, 'utf8');
  const xml = fs.readFileSync(xmlPath, 'utf8');
  const out =
    '/* Generated by pack-assets.js from custom_menu. Do not edit. */\n' +
    `window.MM_BASE_CSS = ${jsString(css)};\n` +
    `window.MM_BASE_XML = ${jsString(xml)};\n`;
  fs.writeFileSync(path.join(dir, 'assets.js'), out);
  return { css, xml };
}

function firstDiff(a, b) {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) {
    if (a[i] !== b[i]) return i;
  }
  return a.length === b.length ? -1 : n;
}

function check(baseCss) {
  const sandbox = { console, TextEncoder, Uint8Array };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(path.join(dir, 'app.js'), 'utf8'), sandbox, { filename: 'app.js' });
  const api = sandbox.MMConstructor;
  if (!api) throw new Error('MMConstructor missing');

  const normalized = baseCss.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
  const same = api.buildCss(api.DEFAULTS, baseCss);
  if (same.warnings.length) {
    throw new Error('default warnings:\n' + same.warnings.join('\n'));
  }
  const body = same.css.replace(/^\/\*[\s\S]*?\*\/\n/, '');
  if (body !== normalized) {
    const at = firstDiff(body, normalized);
    throw new Error(
      'default css drifted at ' + at + '\n' +
      JSON.stringify(body.slice(Math.max(0, at - 80), at + 80)) + '\nVS\n' +
      JSON.stringify(normalized.slice(Math.max(0, at - 80), at + 80))
    );
  }

  const crc = api.crc32(new TextEncoder().encode('123456789'));
  if (crc !== 0xcbf43926) throw new Error('bad crc ' + crc.toString(16));

  const max = {
    ...api.DEFAULTS,
    name: 'Проверка',
    accent: '#112233',
    accentSoft: 'rgba(1, 2, 3, 0.40)',
    frame: 'rgba(4, 5, 6, 0.22)',
    btnBg: 'rgba(7, 8, 9, 0.05)',
    btnHover: 'rgba(7, 8, 9, 0.11)',
    btnActive: 'rgba(7, 8, 9, 0.18)',
    line: 'rgba(10, 11, 12, 0.04)',
    label: '#101112',
    bgTop: 'rgba(13, 14, 15, 0.82)',
    bgBottom: 'rgba(16, 17, 18, 0.86)',
    itemText: '#333333',
    itemValue: '#444444',
    icon: '#555555',
    arrow: '#666666',
    disabledBg: 'rgba(19, 20, 21, 0.62)',
    disabledBorder: 'rgba(22, 23, 24, 0.30)',
    disabledText: '#777777',
    switchOff: 'rgba(25, 26, 27, 0.45)',
    knob: '#111111',
    knobOn: '#abcdab',
    switchOnLinked: false,
    switchOn: '#778899',
    optText: '#222222',
    optHover: 'rgba(28, 29, 30, 0.90)',
    optActive: 'rgba(31, 32, 33, 0.95)',
    selectBg: 'rgba(34, 35, 36, 0.99)',
    selectBorder: 'rgba(37, 38, 39, 0.06)',
    ntfOk: '#00aa00',
    ntfWarn: '#bbbb00',
    ntfErr: '#cc0000',
    ntfBgTop: 'rgba(40, 41, 42, 0.94)',
    ntfBgBottom: 'rgba(43, 44, 45, 0.96)',
    titleLinked: false,
    titleColor: '#445566',
    menuWidth: 444,
    menuRadius: 10,
    btnRadius: 8,
    titleSize: 20,
    titleTracking: 1,
    itemSize: 15,
    descSize: 14,
    itemHeight: 48,
    barWidth: 6,
    anim: 0.2,
    blur: 0,
    dotOpacity: 0.1,
    leftBar: false,
    rightBar: false,
    showDots: false,
    showDesc: false,
    showPagination: false,
    uppercaseTitle: false,
    uppercaseItems: false,
  };

  const built = api.buildCss(max, baseCss);
  if (built.warnings.length) {
    throw new Error('max warnings:\n' + built.warnings.join('\n---\n'));
  }
  const must = [
    '#112233', '#445566', '#778899', '#333333', '#444444', '#555555', '#666666',
    '#111111', '#222222', '#abcdab', '#00aa00', 'width: 444px', 'width: 440px',
    'border-radius: 10px', 'border-radius: 8px', 'font-size: 20px', 'font-size: 15px',
    'font-size: 14px', 'height: 48px', 'height: 336px', 'height: 186px', 'y: 54px',
    'width: 6px', 'dur: 0.2s', 'world-blur: none', 'background-image: none',
    'text-transform: none', '.utils-bar-left { visibility: collapse; }',
    '.utils-desc { visibility: collapse; }', '.utils-pagination { visibility: collapse; }',
    'rgba(13, 14, 15, 0.82)', 'rgba(19, 20, 21, 0.62)',
  ];
  for (const token of must) {
    if (!built.css.includes(token)) throw new Error('missing token ' + token);
  }
  for (const gone of ['#FFA9DE', '#cdd8e4', '#8ea2b4', 'text-transform: uppercase', 'border-radius: 5px', 'border-radius: 4px', 'gaussian(2, 2, 2)']) {
    if (built.css.includes(gone)) throw new Error('still present ' + gone);
  }

  const optOnly = api.buildCss({ ...api.DEFAULTS, optText: "#222222" }, baseCss);
  if (optOnly.warnings.length) throw new Error("opt warnings:\n" + optOnly.warnings.join("\n"));
  if (!optOnly.css.includes("\tcolor: #222222;")) throw new Error("opt color missing");
  if (!optOnly.css.includes("background-color: #cfd4d9;")) throw new Error("knob color was overwritten");

  const zip = api.makeZip([
    { name: 'panorama/styles/custom_game/ui.css', text: built.css },
    { name: 'panorama/layout/custom_game/menu_ui.xml', text: '<root></root>' },
    { name: 'info.txt', text: 'Тема: Проверка' },
  ]);
  const packed = Buffer.from(zip);
  if (!packed.includes(Buffer.from('panorama/styles/custom_game/ui.css'))) throw new Error('zip name missing');
  if (!packed.includes(Buffer.from('#112233'))) throw new Error('zip css missing');
  if (!packed.includes(Buffer.from('Тема: Проверка', 'utf8'))) throw new Error('zip info missing');
  const tmp = path.join(require('os').tmpdir(), 'mm-constructor-test.zip');
  fs.writeFileSync(tmp, packed);
  require('child_process').execFileSync('tar', ['-tf', tmp], { stdio: 'pipe' });
  console.log('constructor check ok', built.css.length, 'bytes css');
}

const assets = writeAssets();
if (process.argv.includes('--check')) check(assets.css);
else console.log('wrote assets.js');
